name: Terraform Drift Detection

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  drift-detection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Drift Check
        id: drift
        run: |
          set +e
          terraform plan -detailed-exitcode
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          exit 0

      - name: Fail if drift detected
        if: steps.drift.outputs.exit_code == '2'
        run: |
          echo "❌ Terraform drift detected!"
          exit 1
